services:
  fastapi-di-backend:
    container_name: fastapi-di-backend
    image: fastapi-di-backend:latest
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - '8000:8000'


  pgdb:
    container_name: pgdb
    hostname: pgdb
    image: postgres:13-alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: root
      POSTGRES_DB: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data: